### PR TITLE
Implements cmd-c when row is selected [related to #11]

### PR DESCRIPTION
**Pull request by oleander**
This pr implements #11.

### CODE REVIEW

**Comment by nathancahill** [comment]
I think there needs to be some visual feedback when copying. Maybe the chooser is dismissed (copy as an alternative to Enter)

**Comment by oleander** [comment]
Sure. How about close and show a message using `hs.alert.show`?

**Comment by nathancahill** [comment]
`hs.alert.show("Copied to clipboard", 0.5)` feels right to me.

**Comment by oleander** [comment]
`0.5` was a bit to fast as I didn't have time to read the message. Would `1` sec work, as used in the update?

**Comment by nathancahill** [comment]
Looks great, thanks!

**Pull request merged**
